### ISSUE TITLE
Templating issues with SQLMeasureProviders

### ISSUE THREAD

**Issue by stillmatic** [airbnb/mensor#19]
hi @matthewwardrop!

running this code with the latest master (basically straight from the docs) gives some errors:

```python
people = (
    SQLMeasureProvider(
        name='people',
        executor=DebugPrestoExecutor
    )
    .add_identifier('person', expr='id', role='primary')
    .add_dimension('name')
    .add_measure('age')
    .add_partition('ds')
)
registry.register(people)

people2 = (
    SQLMeasureProvider(
        name='people2',
        executor=DebugPrestoExecutor
    )
    .add_identifier('person', expr='id', role='unique')
    .add_identifier('geography', expr='id_geography', role='foreign')
    .add_partition('ds')
)
registry.register(people2)

geographies = (
    SQLMeasureProvider(
        name='geographies',
        executor=DebugPrestoExecutor
    )
    .add_identifier('geography', expr='id_geography', role='primary')
    .add_dimension('name')
    .add_measure('population')
    .add_partition('ds')

)
registry.register(geographies)

transactions = (
    SQLMeasureProvider(
        name='transactions',
        executor=DebugPrestoExecutor
    )
    .add_identifier('transaction', expr='id', role='primary')
    .add_identifier('person:buyer', expr='id_buyer', role='foreign')
    .add_identifier('person:seller', expr='id_seller', role='foreign')
    .add_measure('value')
    .add_partition('ds', requires_constraint=True)
)
registry.register(transactions)

transactions.evaluate(
    unit_type='transaction',
    measures=['value'],
    segment_by=['person:seller'],
    where={'ds': '2018-01-01'}
)
```
DebugPrestoExecutor shouldn't matter, we don't even get to a step where SQL is executed.

here's the traceback:
```
Traceback (most recent call last):
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-81-e83c3ba037f6>", line 5, in <module>
    where={'ds': '2018-01-01'}
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/measures/providers/mutable.py", line 249, in wrapped
    return f(self, unit_type, measures=measures, segment_by=segment_by, where=where, joins=joins, stats_registry=stats_registry, stats=stats, covariates=covariates, **opts)
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/measures/providers/mutable.py", line 320, in evaluate
    **opts
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/backends/sql.py", line 249, in _evaluate
    **opts
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/backends/sql.py", line 255, in get_sql
    return self.get_ir(*args, **kwargs)
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/measures/providers/mutable.py", line 249, in wrapped
    return f(self, unit_type, measures=measures, segment_by=segment_by, where=where, joins=joins, stats_registry=stats_registry, stats=stats, covariates=covariates, **opts)
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/measures/providers/mutable.py", line 480, in get_ir
    **opts
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/backends/sql.py", line 261, in _get_ir
    _sql=self._sql(unit_type=unit_type, measures=measures, segment_by=segment_by, where=where, joins=joins, stats=stats, covariates=covariates, **opts),
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/mensor/backends/sql.py", line 231, in _sql
    return self._template_environment.get_template(self._base_sql).render(
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/main_instance_shell/chua/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 316, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: <unprintable TemplateNotFound object>
```

reading this, it seems that when `_base_sql` as passed to `SQLMeasureProvider` is None, then the `_sql` function tries to get a null template and fails. any advice?

**Comment by matthewwardrop** [comment]
Hi @stillmatic ! Thanks for reaching out, and apologies for the long lead time in my response!

The master branch has several refactors and more are incoming; and so things may not be rock solid there. I recommend using the latest "stable" version: 0.3.1. Do you still have issues running on that branch?

**Comment by danfrankj** [comment]
@stillmatic when you evaluate we're stitching together SQL, which in this case has not been provided. I've added some better error handling here: https://github.com/airbnb/mensor/pull/25


To get this working you can add it to the providers ... e.g. 

```
people = (
    SQLMeasureProvider(
        name='people',
        executor=DebugPrestoExecutor,
        sql="""SELECT * FROM dim_users"""
    )
    .add_identifier('person', expr='id', role='primary')
    .add_dimension('name')
    .add_measure('age')
    .add_partition('ds')
)
registry.register(people)
   
```

**Comment by stillmatic** [comment]
Thanks! It wasn't clear to me what to do with the SQL parameter, but that seems easy enough to work with :)
