### ISSUE TITLE
KeyError in quickstart example

### ISSUE THREAD

**Issue by ailurus1991** [airbnb/mensor#23]
Hi @matthewwardrop , I'm running this repo from the quickstart with latest pypi version, and I got a ds key error:

```python
import os
from mensor.measures.registry import MeasureRegistry
from mensor.backends.pandas import PandasMeasureProvider

registry = MeasureRegistry()

data_dir = "<path to checked out Mensor repository>/tests/data"

people = (
    PandasMeasureProvider(
        name='people',
        data=os.path.join(data_dir, 'people.csv')
    )
    .add_identifier('person', expr='id', role='primary')
    .add_dimension('name')
    .add_measure('age')
    .add_partition('ds')
)
registry.register(people)

people2 = (
    PandasMeasureProvider(
        name='people2',
        data=os.path.join(data_dir, 'people.csv')
    )
    .add_identifier('person', expr='id', role='unique')
    .add_identifier('geography', expr='id_geography', role='foreign')
    .add_partition('ds')
)
registry.register(people2)

geographies = (
    PandasMeasureProvider(
        name='geographies',
        data=os.path.join(data_dir, 'geographies.csv')
    )
    .add_identifier('geography', expr='id_geography', role='primary')
    .add_dimension('name')
    .add_measure('population')
    .add_partition('ds')

)
registry.register(geographies)

transactions = (
    PandasMeasureProvider(
        name='transactions',
        data=os.path.join(data_dir, 'transactions.csv')
    )
    .add_identifier('transaction', expr='id', role='primary')
    .add_identifier('person:buyer', expr='id_buyer', role='foreign')
    .add_identifier('person:seller', expr='id_seller', role='foreign')
    .add_measure('value')
    .add_partition('ds', requires_constraint=True)
)
registry.register(transactions)

transactions.evaluate(
    unit_type='transaction',
    measures=['value'],
    segment_by=['person:seller'],
    where={'ds': '2018-01-01'}
)
```
and KeyError:

```bash
Traceback (most recent call last):
  File "/home/guokr/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
 File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
 File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
 File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 66, in <module>
    where={'ds': '2018-01-01'}
  File "/home/guokr/mensor/mensor/measures/providers/mutable.py", line 254, in wrapped
    return f(self, unit_type, measures=measures, segment_by=segment_by, where=where, joins=joins, stats_registry=stats_registry, stats=stats, covariates=covariates, context=context, **opts)
  File "/home/guokr/mensor/mensor/measures/providers/mutable.py", line 329, in evaluate
    **opts
  File "/home/guokr/mensor/mensor/backends/pandas.py", line 69, in _evaluate
    stats_registry=stats_registry, stats=stats, rebase_agg=rebase_agg
  File "/home/guokr/mensor/mensor/backends/pandas.py", line 107, in _finalise_dataframe
    df = cls._apply_where_to_df(df, where)
  File "/home/guokr/mensor/mensor/backends/pandas.py", line 209, in _apply_where_to_df
    return df[cls._get_constraint_for_df(df, where)]
  File "/home/guokr/mensor/mensor/backends/pandas.py", line 214, in _get_constraint_for_df
    return cls._get_constraint_maps()[constraint.kind](df, constraint)
  File "/home/guokr/mensor/mensor/backends/pandas.py", line 230, in <lambda>
    CONSTRAINTS.EQUALITY: lambda df, c: eq(df[c.field], c.value),
  File "/home/guokr/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/guokr/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ds'
```

**Comment by matthewwardrop** [comment]
Hi @ailurus1991! Thanks for trying out mensor! Mensor is not yet super stable, and I'm still mulling over certain aspects of its API. With that said, what works works pretty well.

Unfortunately, a limitation of the current MeasureProvider backend implementations is that they don't request from the data source columns that are only present in the where clause (this is not a limitation of mensor, only its concrete data source implementations). A fix for that will be "coming soon", after I am happy with the rest of the API.

As a work around, you can do:
```
transactions.evaluate(
    unit_type='transaction',
    measures=['value'],
    segment_by=['ds', 'person:seller'],
    where={'ds': '2018-01-01'}
)
```

**Comment by ailurus1991** [comment]
many thanks for the super fast reply!

I tried:
```python
transactions.evaluate(
    unit_type='transaction',
    measures=['value'],
    segment_by=['ds', 'person:seller'],
    where={'ds': '2018-01-01'}
)
```
and I got:
```bash
  File "demo.py", line 66, in <module>
    where={'ds': '2018-01-01'}
  File "/home/guokr/mensor/mensor/measures/providers/mutable.py", line 255, in wrapped
    return f(self, unit_type, measures=measures, segment_by=segment_by, where=where, joins=joins, stats_registry=stats_registry, stats=stats, covariates=covariates, context=context, **opts)
  File "/home/guokr/mensor/mensor/measures/providers/mutable.py", line 329, in evaluate
    **opts
  File "/home/guokr/mensor/mensor/backends/pandas.py", line 59, in _evaluate
    dimension.fieldname(role='dimension', unit_type=unit_type if not rebase_agg else None): raw_data.eval(dimension.expr) for dimension in segment_by
  File "/home/guokr/mensor/mensor/backends/pandas.py", line 59, in <dictcomp>
    dimension.fieldname(role='dimension', unit_type=unit_type if not rebase_agg else None): raw_data.eval(dimension.expr) for dimension in segment_by
  File "/home/guokr/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3203, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/guokr/.local/lib/python3.6/site-packages/pandas/core/computation/eval.py", line 299, in eval
    ret = eng_inst.evaluate()
  File "/home/guokr/.local/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 76, in evaluate
    res = self._evaluate()
  File "/home/guokr/.local/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 123, in _evaluate
    return ne.evaluate(s, local_dict=scope, truediv=truediv)
  File "/home/guokr/.local/lib/python3.6/site-packages/numexpr/necompiler.py", line 822, in evaluate
    zip(names, arguments)]
  File "/home/guokr/.local/lib/python3.6/site-packages/numexpr/necompiler.py", line 821, in <listcomp>
    signature = [(name, getType(arg)) for (name, arg) in
  File "/home/guokr/.local/lib/python3.6/site-packages/numexpr/necompiler.py", line 703, in getType
    raise ValueError("unknown type %s" % a.dtype.name)
ValueError: unknown type object
```
did I miss something or should I install Mensor from master branch?

**Comment by matthewwardrop** [comment]
Hmmm.... That doesn't look good; but also is not surprising. Since v0.3.1, I've torn apart a lot of the API and refactored a whole bunch more; and am still nailing the pieces back together. When v0.4 is released (hopefully later this year), things will be in much better shape. For the time being, I'd use v0.3.1 (which also has limitations), or wait. In its current form, I don't think mensor is ready for production use cases.

**Comment by ailurus1991** [comment]
emmm, after I viewed Mensor's doc, I think I really need this in my data science project flow to save time. If I wanna join, could you show me a simple guide line? cuz I've check Mensor's source code for several hours and I found it's not that easy to understand the class/func design right now..

**Comment by matthewwardrop** [comment]
Hi @ailurus1991 ; I'm thrilled that you are excited by what mensor *will* offer; but it's just not yet ready to be used anywhere where frequent bugs and errors are not okay. It is still my pet research project, and is in alpha status. With the next release (0.4) where I am targetting API completeness, things will be different, but I have no fixed timeline for this release, and lots of things need to be changed before then (but I'd love to see it released sooner rather than later). I'm sorry that this doesn't line up with the timelines for your project :'(.

**Comment by ailurus1991** [comment]
I found this sample data's ds column dtype lead to this KeyError.

in (build Provider's own df)[https://github.com/airbnb/mensor/blob/master/mensor/backends/pandas.py#L59]. I tried `print(raw_data.eval('ds'))`and I got the same error. I think the reason is Pandas's DF cant support eval operation on str dtype column(ds column in the test dataset)

**Comment by matthewwardrop** [comment]
Thanks to @danfrankj , looks like the master branch should work for you now @ailurus1991 . Thanks again for your interest :). I'm hoping to finish up the refactoring work ASAP, after which mensor should become much more stable!
